"""Create "Joker's eye.app" for macOS (default: on the Desktop).

The app is a thin launcher that runs `launch.py` of THIS checkout, so keep the
repository where it is (re-run this tool after moving it). Standard library only.
"""
import argparse
import os
from pathlib import Path
import plistlib
import shutil
import stat
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parent.parent
NAME = "Joker's eye"
BUNDLE_ID = "me.daisan.jokers-eye"

SCRIPT = """#!/bin/sh
# Generated by tools/make_mac_app.py
export PATH="/opt/homebrew/bin:/usr/local/bin:/Library/Frameworks/Python.framework/Versions/Current/bin:/usr/bin:/bin:$PATH"
cd "{root}" || exit 1
exec python3 launch.py "$@"
"""


def make_icns(source, target):
    with tempfile.TemporaryDirectory() as work:
        iconset = Path(work) / "icon.iconset"
        iconset.mkdir()
        for size in (16, 32, 128, 256, 512):
            for scale in (1, 2):
                pixels = size * scale
                name = "icon_%dx%d%s.png" % (size, size, "@2x" if scale == 2 else "")
                subprocess.run(["sips", "-z", str(pixels), str(pixels), str(source), "--out", str(iconset / name)],
                               check=True, stdout=subprocess.DEVNULL)
        subprocess.run(["iconutil", "-c", "icns", str(iconset), "-o", str(target)], check=True)


def build(destination):
    app = Path(destination) / (NAME + ".app")
    if app.exists():
        shutil.rmtree(app)
    macos, resources = app / "Contents" / "MacOS", app / "Contents" / "Resources"
    macos.mkdir(parents=True)
    resources.mkdir()
    executable = macos / "JokersEye"
    executable.write_text(SCRIPT.format(root=ROOT), encoding="utf-8")
    executable.chmod(executable.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    make_icns(ROOT / "web" / "icon.png", resources / "icon.icns")
    version = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
    with open(app / "Contents" / "Info.plist", "wb") as file:
        plistlib.dump({"CFBundleName": NAME, "CFBundleDisplayName": NAME, "CFBundleIdentifier": BUNDLE_ID,
                       "CFBundleExecutable": "JokersEye", "CFBundleIconFile": "icon", "CFBundlePackageType": "APPL",
                       "CFBundleShortVersionString": version, "CFBundleVersion": version,
                       "LSMinimumSystemVersion": "11.0", "NSHighResolutionCapable": True}, file)
    return app


def main():
    if sys.platform != "darwin":
        raise SystemExit("macOS 専用のツールです。")
    parser = argparse.ArgumentParser()
    parser.add_argument("--destination", type=Path, default=Path.home() / "Desktop")
    args = parser.parse_args()
    print(build(args.destination))


if __name__ == "__main__":
    main()
