'use strict';
const pages={overview:['ダッシュボード','観測を積み重ねて、店の輪郭をつかむ。'],data:['データ管理','日付・台番号・機種を、出典とともに残す。'],map:['店内マップ','場所は固定。機種の配置は、日付とともに変わる。'],juggler:['ジャグラー設定推測機','機種別の理論値を参照し、ぶどう逆算と設定推測の入力を整える。'],analysis:['分析ラボ','位置と履歴を、検証できる特徴量へ。'],history:['履歴','取り込んだデータの出典と操作を振り返る。'],versions:['バージョン','ブランチごとの版を選び、本番データのコピーで試す。'],settings:['設定','このPCに、研究の環境を整える。']};
let token=sessionStorage.getItem('joker-token')||'';
const hash=location.hash.slice(1);
if(hash&&!pages[hash]){token=hash;sessionStorage.setItem('joker-token',token);history.replaceState(null,'',location.pathname);}
let page=pages[hash]?hash:'overview',state=null,stopped=false,mapData=null;
const content=document.querySelector('#content');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>v===null?'不明':Number(v||0).toLocaleString('ja-JP');
function notice(msg){const el=document.querySelector('#notice');el.textContent=msg;el.hidden=!msg;}
async function api(path,data){const r=await fetch('/api/'+path,{method:data===undefined?'GET':'POST',headers:{'X-Joker-Token':token,'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const body=await r.json();if(!r.ok)throw Error(body.error||'操作に失敗しました。');return body;}
function button(text,pg,cls='secondary'){return `<button class="${cls}" data-go="${pg}">${text}</button>`;}
function stat(label,value,note){return `<div class="stat"><label>${label}</label><strong>${value}</strong><small>${note}</small></div>`;}
function table(headers,rows){return `<div class="table-scroll"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
async function refresh(){state=await api('state');document.body.classList.toggle('light',state.settings.theme==='light');document.querySelector('#connection').textContent='● ローカル接続';JokersVersions.label(state);}
function overview(){const s=state.summary;return `<section class="hero"><div><div class="kicker">YOUR OBSERVATION STARTS HERE</div><h2>街のクセを、<br>ひとつずつ見抜く。</h2><p>固定の台番号と、移り変わる機種配置。<br>Joker's eye は、ゴッサムシティの記録をつなぐ研究ワークスペースです。</p><div class="actions">${button('データを取得する →','data','primary')}${button('店内マップを見る','map')}</div></div><img src="/icon.png" alt="ダイヤの瞳とジョーカーの冠"></section><section class="stats">${stat('登録レコード',num(s.records),'台 × 日 の観測数')}${stat('データのある日',num(s.days),'連続性・全台網羅は未検証')}${stat('BB・RB取得済み',num(s.withBonus),'BBとRBが両方そろった記録')}${stat('物理マップ',state.mapRegistered?'登録済み':'未登録','配置は現地確認後に登録')}</section><div class="two-cols"><section class="card"><div class="card-header"><h2>最初のワークスペースを整える</h2><span class="tag">GET STARTED</span></div><div class="step"><b>01</b><div><h3>観測データを集める</h3><p>台番号・機種・G数・BB・RB・差枚を公開データから取得してGDBに保存。</p><small>${s.records?'データ登録済み':'次のステップ · データ管理で本日までの分を更新'}</small></div></div><div class="step"><b>02</b><div><h3>固定の場所を定義する</h3><p>島、列、左右の隣接を記録。物理角と機種角を区別。</p><small>マップ編集は次の開発段階</small></div></div><div class="step"><b>03</b><div><h3>履歴を分析につなげる</h3><p>機種の入れ替えと欠損を確認してから、モデルを検証。</p><small>予測モデルは未接続</small></div></div></section><section class="card"><div class="kicker">RESEARCH POLICY</div><h2>この研究の出発点</h2><div class="row"><span>対象店舗</span><strong>ゴッサムシティ</strong></div><div class="row"><span>本番期間の起点</span><strong>2023 / 04 / 27</strong></div><div class="row"><span>それ以前の観測</span><strong>過去資料として保存</strong></div><div class="row"><span>機種と場所</span><strong>設置履歴と固定座席</strong></div><p class="hint">欠けている日は「不明」。登録日の数から連続データの完全性は判断しません。</p></section></div>`;}
function dataPage(){return `<section class="card"><div class="card-header"><h2>登録した観測</h2><span class="tag">${num(state.summary.records)} RECORDS</span></div><div id="observations"><p>読み込み中…</p></div></section><section class="card"><div class="kicker">DATA BOUNDARIES</div><h2>データの扱い</h2><div class="row"><span>2023.04.27 以降</span><strong>本番期間の観測</strong></div><div class="row"><span>2023.04.26 以前</span><strong>過去資料</strong></div><p>取得は記録の保存までです。設定推測、欠損補完、設置期間の自動確定はまだ実行しません。</p></section>`;}
/* 記入例：3/12 金 114 機種 非ジャグラー 3000 12 13 1/120 970 107.3% */
function observationCells(r){const [,m,d]=r['日付'].split('-');const value=v=>v===''?'未取得':v;return [`${+m}/${+d}`,r['曜日'].charAt(0),r['台番号'],r['機種'],r['ジャグラーかジャグラーじゃないか']==='ジャグラー'?'ジャグラー':'非ジャグラー',value(r['ゲーム数']),value(r['BB数']),value(r['RB数']),value(r['合成']),value(r['差枚']),value(r['出率'])];}
async function loadObservations(day=''){const result=await api('observations'+(day?'?date='+encodeURIComponent(day):''));if(page!=='data')return;const target=document.querySelector('#observations');target.innerHTML=result.days.length?`<div class="toolbar"><label for="day-select">表示日</label><select id="day-select">${result.days.map(d=>`<option ${d===result.selected?'selected':''}>${esc(d)}</option>`).join('')}</select><span class="hint">${result.rows.length} 台の観測</span></div>${table(['日付','曜日','台番号','機種','ジャグラーか','ゲーム数','BB数','RB数','合成','差枚','出率'],result.rows.map(observationCells))}`:'<div class="empty"><div class="symbol">▤</div><h2>まだ観測データがありません</h2><p>公開データを取得すると、ここに台ごとの記録が表示されます。</p></div>';document.querySelector('#day-select')?.addEventListener('change',e=>loadObservations(e.target.value).catch(showError));}
function mapPage(){queueMicrotask(()=>loadSeatMap().catch(showError));return `<section class="card"><div class="card-header"><div><div class="kicker">GOTHAM CITY / FLOOR MAPS</div><h2 id="map-view-title">店内マップ</h2></div><span class="tag">${num(state.mapPeriods)} PERIODS</span></div><div id="floor-map-content"><p class="muted">配置履歴を読み込み中…</p></div></section>`;}
async function loadSeatMap(){const root=document.querySelector('#floor-map-content');if(root)await JokersMap.mount(root,api);}
function versionsPage(){queueMicrotask(()=>{const root=document.querySelector('#versions-content');if(root)JokersVersions.mount(root).catch(showError);});return '<div id="versions-content"></div>';}
function jugglerPage(){queueMicrotask(()=>{const root=document.querySelector('#juggler-content');if(root)JokersJuggler.mount(root).catch(showError);});return '<div id="juggler-content"></div>';}
function analysisPage(){return `<section class="card"><div class="empty"><div class="symbol">⌁</div><h2>分析の前に、観測を整える。</h2><p>このバージョンはアプリの基盤です。高設定確率や台の推薦はまだ計算していません。データの網羅性と物理配置を確認した後に実装します。</p><div class="actions">${button('データ管理へ','data','primary')}</div></div></section><div class="roadmap"><section class="card"><span class="tag">PLANNED</span><h2>設定推測</h2><p>機種別の確率とG数・BB・RBから、不確実性を含む推定へ。</p></section><section class="card"><span class="tag">PLANNED</span><h2>位置・投入傾向</h2><p>物理角、機種角、並びを考慮して傾向を検証。</p></section><section class="card"><span class="tag">PLANNED</span><h2>時系列の検証</h2><p>予測時点で使える情報だけを使用し、入力条件と結果を履歴に保存。</p></section></div>`;}
function runDuration(s){if(s===null||s===undefined)return '—';if(s<60)return `${Math.round(s*10)/10}秒`;s=Math.round(s);const h=Math.floor(s/3600),m=Math.floor(s%3600/60),r=s%60;return (h?`${h}時間`:'')+`${m}分`+(h?'':`${r}秒`);}
function historyPage(){const states={complete:'完了',stopped:'停止',failed:'失敗（停止）',interrupted:'中断',running:'取得中'};return `<section class="card"><div class="card-header"><h2>データ取得の履歴</h2><span class="tag">最新100件</span></div>${state.runs.length?table(['開始日時','結果','所要時間','処理日数','1日あたり','停止事由','対象期間','メッセージ'],state.runs.map(r=>[new Date(r.started_at).toLocaleString('ja-JP'),states[r.state]||r.state,runDuration(r.elapsed_seconds),r.days_done===null||r.days_done===undefined?'—':num(r.days_done)+' 日',runDuration(r.seconds_per_day),r.stop_reason||(r.state==='complete'?'—':''),`${r.start_day||'—'} ～ ${r.end_day||'—'}`,r.message||''])):'<div class="empty"><div class="symbol">◷</div><h2>ここに研究の履歴が残ります</h2><p>公開データを取得すると、実行日時・結果・対象期間を確認できます。</p></div>'}</section><section class="card"><h2>分析実行の履歴</h2><p>分析機能の実装後に、条件と結果を再表示する履歴を追加します。</p></section>`;}
function settingsPage(){return `<div class="two-cols"><section class="card"><div class="kicker">PREFERENCES</div><h2>ワークスペース設定</h2><form id="settings-form"><label class="label" for="theme">表示テーマ</label><select id="theme"><option value="dark" ${state.settings.theme!=='light'?'selected':''}>ミッドナイト</option><option value="light" ${state.settings.theme==='light'?'selected':''}>ライト</option></select><label class="label" for="notes">研究メモ</label><textarea id="notes" maxlength="10000" placeholder="次に確認したいこと、観測上の注意点…">${esc(state.settings.notes||'')}</textarea><div class="actions"><button class="primary">設定を保存</button></div></form></section><section class="card"><div class="kicker">LOCAL STORAGE</div><h2>データとバックアップ</h2><p>設定と観測データは、このPCのデータベース <b>${esc(state.databaseFile)}</b>（GDB）に保存しています。</p><div class="path">${esc(state.dataPath)}</div><div class="actions"><button id="backup" class="secondary">バックアップを作成 ↓</button></div><p class="hint">バックアップは上記フォルダー内の backups に保存します。</p><div class="row"><span>バージョン</span><strong>${esc(state.version)} / Floor map</strong></div><div class="row"><span>番号・機種対応</span><strong>${num(state.mapSeats)} 台</strong></div><div class="row"><span>動作方式</span><strong>ローカル専用</strong></div></section></div>`;}
function showError(e){notice(e.message||String(e));}
function navigate(next){if(!state)return;page=next;notice('');document.querySelector('#page-title').textContent=pages[page][0];document.querySelector('#page-subtitle').textContent=pages[page][1];document.querySelectorAll('nav button').forEach(b=>{b.classList.toggle('active',b.dataset.page===page);b.setAttribute('aria-current',b.dataset.page===page?'page':'false');});content.innerHTML=({overview,data:dataPage,map:mapPage,juggler:jugglerPage,versions:versionsPage,analysis:analysisPage,history:historyPage,settings:settingsPage}[page])();document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.go)));if(page==='data'){loadObservations().catch(showError);}if(page==='settings'){document.querySelector('#settings-form').addEventListener('submit',async e=>{e.preventDefault();try{await api('settings',{theme:document.querySelector('#theme').value,notes:document.querySelector('#notes').value});await refresh();notice('設定を保存しました。');}catch(ex){showError(ex);}});document.querySelector('#backup').addEventListener('click',async()=>{try{const r=await api('backup',{});notice('バックアップを保存しました。\n'+r.path);}catch(ex){showError(ex);}});}window.scrollTo(0,0);}
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.page)));
document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();navigate('overview');});
document.querySelector('#today').textContent=new Date().toLocaleDateString('ja-JP',{year:'numeric',month:'long',day:'numeric',weekday:'short'});
document.querySelector('#shutdown').addEventListener('click',async()=>{try{await api('shutdown',{});stopped=true;document.querySelector('#connection').textContent='終了しました';notice('アプリを終了しました。このウィンドウを閉じてください。');document.querySelectorAll('button').forEach(b=>b.disabled=true);window.chrome?.webview?.postMessage('close');}catch(ex){showError(ex);}});
setInterval(()=>{if(!stopped)api('heartbeat',{}).catch(()=>{document.querySelector('#connection').textContent='接続が切れました';});},20000);
refresh().then(()=>{api('heartbeat',{}).catch(showError);navigate(page);}).catch(ex=>{document.querySelector('#connection').textContent='接続できません';notice(ex.message+' Joker’s eyeを開き直してください。');});
