'use strict';
const pages={overview:['ダッシュボード','観測を積み重ねて、店の輪郭をつかむ。'],data:['データ管理','日付・台番号・機種・貸区分を、出典とともに残す。'],map:['店内マップ','場所は固定。機種の配置は、日付とともに変わる。'],juggler:['ジャグラー設定推測機','機種別の理論値を参照し、ぶどう逆算と設定推測の入力を整える。'],analysis:['分析ラボ','位置と履歴を、検証できる特徴量へ。'],history:['履歴','取り込んだデータの出典と操作を振り返る。'],settings:['設定','このPCに、研究の環境を整える。']};
let token=sessionStorage.getItem('joker-token')||'';
const hash=location.hash.slice(1);
if(hash&&!pages[hash]){token=hash;sessionStorage.setItem('joker-token',token);history.replaceState(null,'',location.pathname);}
let page=pages[hash]?hash:'overview',state=null,stopped=false,mapData=null;
const content=document.querySelector('#content');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>v===null?'不明':Number(v||0).toLocaleString('ja-JP');
function notice(msg){const el=document.querySelector('#notice');el.textContent=msg;el.hidden=!msg;}
async function api(path,data){const r=await fetch('/api/'+path,{method:data===undefined?'GET':'POST',headers:{'X-Joker-Token':token,'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const body=await r.json();if(!r.ok)throw Error(body.error||'操作に失敗しました。');return body;}
function button(text,pg,cls='secondary'){return `<button class="${cls}" data-go="${pg}">${text}</button>`;}
function stat(label,value,note){return `<div class="stat"><label>${label}</label><strong>${value}</strong><small>${note}</small></div>`;}
function table(headers,rows){return `<div class="table-scroll"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
async function refresh(){state=await api('state');document.body.classList.toggle('light',state.settings.theme==='light');document.querySelector('#connection').textContent='● ローカル接続';}
function overview(){const s=state.summary;return `<section class="hero"><div><div class="kicker">YOUR OBSERVATION STARTS HERE</div><h2>街のクセを、<br>ひとつずつ見抜く。</h2><p>固定の台番号と、移り変わる機種配置。<br>Joker's eye は、ゴッサムシティの記録をつなぐ研究ワークスペースです。</p><div class="actions">${button('データを取り込む →','data','primary')}${button('店内マップを見る','map')}</div></div><img src="/icon.png" alt="ダイヤの瞳とジョーカーの冠"></section><section class="stats">${stat('登録レコード',num(s.records),'台 × 日 の観測数')}${stat('データのある日',num(s.days),'連続性・全台網羅は未検証')}${stat('本番期間の主貸区分',num(s.main),'2023.04.27 以降')}${stat('物理マップ',state.mapRegistered?'登録済み':'未登録','配置は現地確認後に登録')}</section><div class="two-cols"><section class="card"><div class="card-header"><h2>最初のワークスペースを整える</h2><span class="tag">GET STARTED</span></div><div class="step"><b>01</b><div><h3>観測データを集める</h3><p>台番号・機種・G数・BB・RB・差枚をCSVから保存。</p><small>${s.records?'データ登録済み':'次のステップ · CSVを取り込む'}</small></div></div><div class="step"><b>02</b><div><h3>固定の場所を定義する</h3><p>島、列、左右の隣接を記録。物理角と機種角を区別。</p><small>マップ編集は次の開発段階</small></div></div><div class="step"><b>03</b><div><h3>履歴を分析につなげる</h3><p>機種の入れ替えと欠損を確認してから、モデルを検証。</p><small>予測モデルは未接続</small></div></div></section><section class="card"><div class="kicker">RESEARCH POLICY</div><h2>この研究の出発点</h2><div class="row"><span>対象店舗</span><strong>ゴッサムシティ</strong></div><div class="row"><span>本番期間の起点</span><strong>2023 / 04 / 27</strong></div><div class="row"><span>それ以前の観測</span><strong>過去資料として保存</strong></div><div class="row"><span>貸メダル区分</span><strong>主貸区分・低貸・不明</strong></div><div class="row"><span>機種と場所</span><strong>設置履歴と固定座席</strong></div><p class="hint">欠けている日は「不明」。登録日の数から連続データの完全性は判断しません。</p></section></div>`;}
function dataPage(){return `<div class="two-cols"><section class="card"><div class="kicker">IMPORT OBSERVATIONS</div><h2>CSVを取り込む</h2><p>UTF-8のCSVを選んで、出典とともにローカルDBへ保存します。</p><form id="import-form"><label class="label" for="csv">CSVファイル</label><input id="csv" type="file" accept=".csv,text/csv" required><label class="label" for="source">出典 / メモ</label><input id="source" type="text" placeholder="例：みんレポの掲載URL、取得日" required maxlength="1000"><p class="hint">date, seat, model, games, bb, rb, net, rate<br>貸区分：main / low / unknown。差枚不明は空欄。<br>同じ日付・台番号があれば取込全体を中止します。</p><div class="actions"><button class="primary" type="submit">データを保存</button><a class="secondary" href="/template.csv" download="jokers-eye-template.csv">CSVテンプレート ↓</a></div></form></section><section class="card"><div class="kicker">DATA BOUNDARIES</div><h2>データの扱い</h2><div class="row"><span>2023.04.27 以降</span><strong>本番期間の観測</strong></div><div class="row"><span>2023.04.26 以前</span><strong>過去資料</strong></div><div class="row"><span>貸区分が不明</span><strong>学習対象を確定しない</strong></div><p>取り込みは記録の保存までです。設定推測、欠損補完、設置期間の自動確定はまだ実行しません。</p></section></div><section class="card"><div class="card-header"><h2>登録した観測</h2><span class="tag">${num(state.summary.records)} RECORDS</span></div><div id="observations"><p>読み込み中…</p></div></section>`;}
async function loadObservations(day=''){const result=await api('observations'+(day?'?date='+encodeURIComponent(day):''));if(page!=='data')return;const target=document.querySelector('#observations');target.innerHTML=result.days.length?`<div class="toolbar"><label for="day-select">表示日</label><select id="day-select">${result.days.map(d=>`<option ${d===result.selected?'selected':''}>${esc(d)}</option>`).join('')}</select><span class="hint">${result.rows.length} 台の観測</span></div>${table(['台番号','機種','G数','BB','RB','差枚','貸区分'],result.rows.map(r=>[r.seat,r.model,num(r.games),r.bb,r.rb,r.net===null?'不明':num(r.net),{main:'主貸区分',low:'低貸',unknown:'不明'}[r.rate]]))}`:'<div class="empty"><div class="symbol">▤</div><h2>まだ観測データがありません</h2><p>CSVを取り込むと、ここに台ごとの記録が表示されます。</p></div>';document.querySelector('#day-select')?.addEventListener('change',e=>loadObservations(e.target.value).catch(showError));}
function mapPage(){queueMicrotask(()=>loadSeatMap().catch(showError));return `<section class="card"><div class="card-header"><div><div class="kicker">GOTHAM CITY / FLOOR MAPS</div><h2 id="map-view-title">店内マップ</h2></div><span class="tag">${num(state.mapPeriods)} PERIODS</span></div><div id="floor-map-content"><p class="muted">配置履歴を読み込み中…</p></div></section>`;}
async function loadSeatMap(){const root=document.querySelector('#floor-map-content');if(root)await JokersMap.mount(root,api);}
function jugglerPage(){queueMicrotask(()=>{const root=document.querySelector('#juggler-content');if(root)JokersJuggler.mount(root).catch(showError);});return '<div id="juggler-content"></div>';}
function analysisPage(){return `<section class="card"><div class="empty"><div class="symbol">⌁</div><h2>分析の前に、観測を整える。</h2><p>このバージョンはアプリの基盤です。高設定確率や台の推薦はまだ計算していません。データの網羅性と物理配置を確認した後に実装します。</p><div class="actions">${button('データ管理へ','data','primary')}</div></div></section><div class="roadmap"><section class="card"><span class="tag">PLANNED</span><h2>設定推測</h2><p>機種別の確率とG数・BB・RBから、不確実性を含む推定へ。</p></section><section class="card"><span class="tag">PLANNED</span><h2>位置・投入傾向</h2><p>物理角、機種角、並び、貸区分を考慮して傾向を検証。</p></section><section class="card"><span class="tag">PLANNED</span><h2>時系列の検証</h2><p>予測時点で使える情報だけを使用し、入力条件と結果を履歴に保存。</p></section></div>`;}
function historyPage(){return `<section class="card"><div class="card-header"><h2>データ取込履歴</h2><span class="tag">最新100件</span></div>${state.imports.length?table(['取込日時','ファイル','行数','出典'],state.imports.map(r=>[new Date(r.created_at).toLocaleString('ja-JP'),r.filename,num(r.rows),r.source])):'<div class="empty"><div class="symbol">◷</div><h2>ここに研究の履歴が残ります</h2><p>CSVを保存すると、取込日時・ファイル・件数・出典を確認できます。</p></div>'}</section><section class="card"><h2>分析実行の履歴</h2><p>分析機能の実装後に、条件と結果を再表示する履歴を追加します。</p></section>`;}
function settingsPage(){return `<div class="two-cols"><section class="card"><div class="kicker">PREFERENCES</div><h2>ワークスペース設定</h2><form id="settings-form"><label class="label" for="theme">表示テーマ</label><select id="theme"><option value="dark" ${state.settings.theme!=='light'?'selected':''}>ミッドナイト</option><option value="light" ${state.settings.theme==='light'?'selected':''}>ライト</option></select><label class="label" for="notes">研究メモ</label><textarea id="notes" maxlength="10000" placeholder="次に確認したいこと、観測上の注意点…">${esc(state.settings.notes||'')}</textarea><div class="actions"><button class="primary">設定を保存</button></div></form></section><section class="card"><div class="kicker">LOCAL STORAGE</div><h2>データとバックアップ</h2><p>設定と観測データは、このPCのSQLiteデータベースに保存しています。</p><div class="path">${esc(state.dataPath)}</div><div class="actions"><button id="backup" class="secondary">バックアップを作成 ↓</button></div><p class="hint">バックアップは上記フォルダー内の backups に保存します。</p><div class="row"><span>バージョン</span><strong>${esc(state.version)} / Floor map</strong></div><div class="row"><span>番号・機種対応</span><strong>${num(state.mapSeats)} 台</strong></div><div class="row"><span>動作方式</span><strong>ローカル専用</strong></div></section></div>`;}
function showError(e){notice(e.message||String(e));}
function navigate(next){if(!state)return;page=next;notice('');document.querySelector('#page-title').textContent=pages[page][0];document.querySelector('#page-subtitle').textContent=pages[page][1];document.querySelectorAll('nav button').forEach(b=>{b.classList.toggle('active',b.dataset.page===page);b.setAttribute('aria-current',b.dataset.page===page?'page':'false');});content.innerHTML=({overview,data:dataPage,map:mapPage,juggler:jugglerPage,analysis:analysisPage,history:historyPage,settings:settingsPage}[page])();document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.go)));if(page==='data'){loadObservations().catch(showError);document.querySelector('#import-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const file=document.querySelector('#csv').files[0];if(file.size>9*1024*1024)throw Error('CSVは9MB以下にしてください。');const text=new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer());const r=await api('import',{text,filename:file.name,source:document.querySelector('#source').value});await refresh();navigate('data');notice(`${num(r.rows)}件の観測を保存しました。`);}catch(ex){showError(ex);}finally{b.disabled=false;}});}if(page==='settings'){document.querySelector('#settings-form').addEventListener('submit',async e=>{e.preventDefault();try{await api('settings',{theme:document.querySelector('#theme').value,notes:document.querySelector('#notes').value});await refresh();notice('設定を保存しました。');}catch(ex){showError(ex);}});document.querySelector('#backup').addEventListener('click',async()=>{try{const r=await api('backup',{});notice('バックアップを保存しました。\n'+r.path);}catch(ex){showError(ex);}});}window.scrollTo(0,0);}
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.page)));
document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();navigate('overview');});
document.querySelector('#today').textContent=new Date().toLocaleDateString('ja-JP',{year:'numeric',month:'long',day:'numeric',weekday:'short'});
document.querySelector('#shutdown').addEventListener('click',async()=>{try{await api('shutdown',{});stopped=true;document.querySelector('#connection').textContent='終了しました';notice('アプリを終了しました。このウィンドウを閉じてください。');document.querySelectorAll('button').forEach(b=>b.disabled=true);window.chrome?.webview?.postMessage('close');}catch(ex){showError(ex);}});
setInterval(()=>{if(!stopped)api('heartbeat',{}).catch(()=>{document.querySelector('#connection').textContent='接続が切れました';});},20000);
refresh().then(()=>{api('heartbeat',{}).catch(showError);navigate(page);}).catch(ex=>{document.querySelector('#connection').textContent='接続できません';notice(ex.message+' Joker’s eyeを開き直してください。');});
